### PR TITLE
JBQA-13277 - Jetty HTTP2 client proposal capable of storing pushed

### PR DESCRIPTION
**Pull request by tremes**
resources URLs.

### CODE REVIEW

**Comment by rhatlapa** [comment]
I've tried the code with Undertow and it fails for me with
```
 - Execution interrupted: null
org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:130)
jmeter.plugins.http2.sampler.JettyHttp2Client.sendRequest(JettyHttp2Client.java:60)
jmeter.plugins.http2.sampler.HTTP2Sampler.sample(HTTP2Sampler.java:295)
jmeter.plugins.http2.sampler.HTTP2Sampler.sample(HTTP2Sampler.java:189)
org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
java.lang.Thread.run(Thread.java:745)
```

and less often with 
```
- Execution interrupted: org.eclipse.jetty.io.RuntimeIOException: javax.net.ssl.SSLHandshakeException: Unrecognized SSL message, plaintext connection?
org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:138)
jmeter.plugins.http2.sampler.JettyHttp2Client.sendRequest(JettyHttp2Client.java:60)
jmeter.plugins.http2.sampler.HTTP2Sampler.sample(HTTP2Sampler.java:295)
jmeter.plugins.http2.sampler.HTTP2Sampler.sample(HTTP2Sampler.java:189)
org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
java.lang.Thread.run(Thread.java:745)
```

**Comment by rhatlapa** [comment]
Please ignore my last comment which I have deleted. It was caused by running the jmeter by mistake against 8080 (plain http)

**Comment by rhatlapa** [comment]
I've noticed one strange behavior, when doing request `http://localhost:8443/undertow-perf-test-app/dynamic.jsp`, notice usage of `http` with port requiring ssl, then the plugin considers this successful samples. On the other hand when I use e.g. curl, I get `curl: (52) Empty reply from server`. 
By looking at the jmeter plugin code and jmeter logs, I can see that the response in jmeter.plugins.http2.sampler.JettyHttp2Client.OpenStreamListener#onHeaders is 200. Maybe some jetty special behavior or bug? At least I would expect the request to fail in such case.

**Comment by tremes** [comment]
Actually it's a good point. I think the important question is how to handle response code in various cases. It looks like headers were received correctly in the case you described above but there was not data response (this case is currently not taken into account by the client)?Is it possible? 
I need to investigate this. Thanks

**Comment by tremes** [comment]
Should be fixed now.

**Review by rhatlapa — APPROVED** [review]
Thanks, LGTM, further improvements shall be done in new commits/PRs

**Pull request merged**
